### ISSUE TITLE
Any way to get more data?

### ISSUE THREAD

**Issue by lando-cal** [gregsqueeb/consultDash#11]
I'm interested in checking quite a bit more of the Consult data. MAF/MAP sensors, for instance. Is the byte ordering proprietary information, or do you happen to know where to get it for other components?

Awesome work, BTW. I sure wish something like this was around for the old ALDL systems. OBD2 is almost useful, but there's so many proprietary PID's! Nice to see someone helping to open up the automotive systems.

**Comment by gregsqueeb** [comment]
Yep! Here are some good resources for pulling more data out of the consult port: 
https://github.com/fridlington/K11Consult/blob/master/Consult_Protocol_%26_Commands_Issue_6.pdf
https://github.com/fridlington/K11Consult/blob/master/Generic_Nissan_ECU_Sensor_or_Data_register_table_Ver_2.pdf
