### ISSUE TITLE
not an issue! might be what i'm looking for..

### ISSUE THREAD

**Issue by georgefell86** [gregsqueeb/consultDash#13]
Hey Greg,

Love what you have done with the dash, I was wondering if it could read an OBD2 port aswell/instead? no nothing about coding etc. but got just enough smarts to install stuff onto the pi.

Looking for a cheap way to do a custom dash in my race car and this looks awesome...

Thanks

**Comment by gregsqueeb** [comment]
Hey! Unfortunately it is made specifically for OB1 and does not support
OBDII

Greg

**Comment by georgefell86** [comment]
No worries, thank you for coming back to me!
