### ISSUE TITLE
Video link and component hardware list?

### ISSUE THREAD

**Issue by jorvis** [gregsqueeb/consultDash#2]
Would you consider updating the README to include both your [helpful video](https://www.youtube.com/watch?v=5C9ypE6JUuY) but also provide a list of links of the components to buy that you referenced?  I'm going to try this with a BeagleBone Black I have lying around with a touchscreen already on it, but the hardware list might be helpful for others.

**Comment by jorvis** [comment]
I just realized these were in the YouTube video, so I added these to the README here and make a pull request.

**Comment by gregsqueeb** [comment]
Thanks again!
