### ISSUE TITLE
npm run dev 

### ISSUE THREAD

**Issue by harshp45** [gregsqueeb/consultDash#7]
> hello-world@ dev /home/pi/consultDash
> NODE_ENV=development node server.js

Server listening on port 8090 

“After these nothing happens on screen”
“No such window of dash gets opened on screen”

PLEASE HELP ME TO SOLVE THE ISSUE

**Comment by gregsqueeb** [comment]
What environment are you trying to set this up on? Are you doing this on a RPI? Try opening localhost:8090 in a browser and see if you can see the dash.

**Comment by harshp45** [comment]
Thanks for the guidance. Now it Runs Successfully. @gregsqueeb
